name: Emacs ox-publish
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Emacs
        run: sudo apt-get update && sudo apt-get install -y emacs-nox

      - name: Publish Org to HTML
        run: emacs --batch --load publish.el --funcall org-publish-all

      - name: Commit and Push
        run: |
          git config --global user.name 'valeria-bot'
          git config --global user.email 'valeria@cs.research'
          git add .
          if git diff --staged --quiet; then
            echo "Sin cambios."
          else
            git commit -m "docs: emacs-publish [skip ci]"
            git push origin main
          fi